<a href="https://colab.research.google.com/github/yunyeong-choi/2022fin/blob/master/%ED%8C%8C%EC%9D%B4%EC%8D%AC%EC%9C%BC%EB%A1%9C%20%EB%B0%B0%EC%9A%B0%EB%8A%94%20%EC%8B%A4%EC%A0%84%20%EA%B8%88%EC%9C%B5%20%EB%8D%B0%EC%9D%B4%ED%84%B0%20%EB%B6%84%EC%84%9D(%ED%80%80%ED%8A%B8)/2%EA%B0%95_%EA%B8%88%EC%9C%B5_%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B6%84%EC%84%9D%EC%9D%84_%EC%9C%84%ED%95%9C_%EB%84%98%ED%8C%8C%EC%9D%B4(Numpy)_%ED%8C%90%EB%8B%A4%EC%8A%A4(Pandas)_%EC%8B%A4%EC%8A%B5_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Numpy

#### numpy 기본 1. 다차원 배열 만들기

In [1]:
# numpy 임포트
import numpy as np

In [2]:
# 1차원 배열 생성하기
넘파이_배열1 = np.array([1,2,3,4])
넘파이_배열1

array([1, 2, 3, 4])

In [3]:
# 2차원 배열 생성하기
넘파이_배열2 = np.array([[1,2,3,4],[11,12,13,14]])
넘파이_배열2

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14]])

In [4]:
# 3차원 배열 생성하기
넘파이_배열3 = np.array([ [[1,2,3,4],[11,12,13,14]],
                [[21,22,23,24],[31,32,33,34]] ])
넘파이_배열3

array([[[ 1,  2,  3,  4],
        [11, 12, 13, 14]],

       [[21, 22, 23, 24],
        [31, 32, 33, 34]]])

In [5]:
# 배열의 모양 보기
print(넘파이_배열1.shape)
print(넘파이_배열2.shape)
print(넘파이_배열3.shape)

(4,)
(2, 4)
(2, 2, 4)


In [6]:
z1 = np.zeros([4])    # 0 으로 채운 배열 만들기
o2 = np.ones([3,4])   # 1 로 채운 배열 만들기
r2 = np.random.randn(2,3).round(2)   # 랜덤한 숫자 배열 만들기

In [7]:
z1, o2, r2

(array([0., 0., 0., 0.]), array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]), array([[-1.85,  1.7 , -0.5 ],
        [-0.25, -0.86, -0.07]]))

In [8]:
# 배열의 모양 보기
print(z1.shape)
print(o2.shape)
print(r2.shape)

(4,)
(3, 4)
(2, 3)


In [9]:
# 무척 큰 4차원 배열 생성해보기
r4 = np.random.randn(2,2,4,5).round(3)
r4

array([[[[ 1.012, -1.058, -0.064, -0.878, -0.241],
         [-0.989,  0.655,  2.25 ,  0.591,  0.142],
         [ 1.311,  0.112,  0.21 ,  0.779,  0.601],
         [-0.119,  3.536,  0.963, -0.254, -1.705]],

        [[-0.641,  0.509,  0.555, -0.167, -1.054],
         [ 0.78 , -0.794,  0.147, -0.96 ,  2.112],
         [ 0.755, -1.389,  2.235,  0.601, -0.891],
         [-1.213, -0.706,  1.237,  0.5  , -0.104]]],


       [[[ 0.671,  0.057, -2.074,  0.399, -0.099],
         [-0.339,  0.077, -0.105,  1.203, -1.625],
         [-0.871,  0.556, -1.008,  0.538, -0.864],
         [-1.257,  0.449, -0.089,  0.085,  1.55 ]],

        [[-1.738, -0.777,  1.246,  0.601,  0.058],
         [-2.131, -0.376, -0.137, -0.665,  0.626],
         [ 1.427,  0.524, -0.274,  0.884,  0.983],
         [ 0.405,  0.043, -0.886, -0.454,  0.356]]]])

#### numpy 기본 2. Indexing과 Slicing

In [10]:
# r4 배열에서, [두번째][첫번째] 접근해서 가져오기
r4[1][0]

array([[ 0.671,  0.057, -2.074,  0.399, -0.099],
       [-0.339,  0.077, -0.105,  1.203, -1.625],
       [-0.871,  0.556, -1.008,  0.538, -0.864],
       [-1.257,  0.449, -0.089,  0.085,  1.55 ]])

In [12]:
r4[1][0][2]

array([-0.871,  0.556, -1.008,  0.538, -0.864])

In [13]:
r4[1][0][2][4]

-0.864

In [14]:
r4[1,0,2,4]   # 대괄호 대신 쉼표 , 도 차원 접근이 가능

-0.864

In [15]:
r4[1][0][2][0:4:2]

array([-0.871, -1.008])

In [16]:
r4[1][0][1:4:2]

array([[-0.339,  0.077, -0.105,  1.203, -1.625],
       [-1.257,  0.449, -0.089,  0.085,  1.55 ]])

In [17]:
# Indexing과 Slicing 같이 적용하기
r4[1][0][1:4:2][1][3:]

array([0.085, 1.55 ])

In [18]:
r4[1,0][1:4:2][1,3:]   # 모두 다 짬뽕!!

array([0.085, 1.55 ])

#### Broadcasting

In [19]:
arr = np.array([[1,2,3,4],[10,11,12,13]])
arr

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13]])

In [20]:
arr + arr    # 배열끼리 연산하기 (＋－*/ 모두 가능)

array([[ 2,  4,  6,  8],
       [20, 22, 24, 26]])

In [21]:
arr + 20     # 덧셈 브로드캐스팅

array([[21, 22, 23, 24],
       [30, 31, 32, 33]])

In [22]:
arr * 100    # 곱셈 브로드캐스팅

array([[ 100,  200,  300,  400],
       [1000, 1100, 1200, 1300]])

In [23]:
# 배열 전체의 덧셈, 평균, 곱셈, 최댓값, 최솟값
arr.sum(), arr.mean(), arr.prod(), arr.max(), arr.min()

(56, 7.0, 411840, 13, 1)

In [24]:
# 배열에서의 최대인 원소의 번호, 최소인 원소의 번호
arr.argmax(), arr[1].argmax(), arr.argmin()

(7, 3, 0)

In [25]:
# 특정 축(차원)으로 덧셈 수행하기
arr.sum(axis=0), arr.sum(axis=1)

(array([11, 13, 15, 17]), array([10, 46]))

In [26]:
# Indexing + Slicing + Aggregation 응용
arr[1].min(), arr[1][2:].sum()

(10, 25)

#### numpy 기본 4. 고급 Broadcasting

In [27]:
arr1 = np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]])
arr2 = np.array([[0,1,2],[0,1,2],[0,1,2],[0,1,2]])
arr1.shape, arr2.shape

((4, 3), (4, 3))

In [28]:
arr1 + arr2          # (4x3)  +  (4x3)

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [29]:
arr1 + np.array([0,1,2])     # (4x3) + (1x3)

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

### Pandas

#### pandas 기본 1. 『 Series 』 행×값 데이터 

In [30]:
# pandas 임포트
import pandas as pd

#### 예제 주식 데이터 csv 파일 다운로드


In [31]:
!wget "https://gist.githubusercontent.com/solaris33/e9938d2f36969a28b5cf15dfc17a77b3/raw/402e4494a6a0cce7d1d1d543cb5d9ac7831c6d1b/stock.adj_close.csv" -O "stock.adj_close.csv"

--2022-09-28 06:07:07--  https://gist.githubusercontent.com/solaris33/e9938d2f36969a28b5cf15dfc17a77b3/raw/402e4494a6a0cce7d1d1d543cb5d9ac7831c6d1b/stock.adj_close.csv
Resolving gist.githubusercontent.com (gist.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to gist.githubusercontent.com (gist.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9051250 (8.6M) [text/plain]
Saving to: ‘stock.adj_close.csv’

stock.adj_close.csv 100%[===================>]   8.63M  --.-KB/s    in 0.1s    

2022-09-28 06:07:08 (60.1 MB/s) - ‘stock.adj_close.csv’ saved [9051250/9051250]



In [32]:
# 주가 데이터를 불러오고, series 하나를 고릅니다.
주가_데이터 = pd.read_csv('stock.adj_close.csv', index_col=0)
my_series = 주가_데이터.loc['A005930']['2020-09-09':]

In [33]:
my_series    # Series

2020-09-09    58400.0
2020-09-10    59200.0
2020-09-11    59000.0
2020-09-14    60400.0
2020-09-15    61000.0
2020-09-16    61000.0
2020-09-17    59500.0
2020-09-18    59300.0
Name: A005930, dtype: float64

In [34]:
my_series.index    # Series의 인덱스 보기

Index(['2020-09-09', '2020-09-10', '2020-09-11', '2020-09-14', '2020-09-15',
       '2020-09-16', '2020-09-17', '2020-09-18'],
      dtype='object')

In [35]:
my_series.name    # Series의 이름 보기

'A005930'

In [36]:
type(my_series)    # 타입 확인하기

pandas.core.series.Series

#### pandas 기본 2. 『 Series 』   접근, 연산, 생성

In [37]:
my_series.loc['2020-09-15']   # 인덱스로 접근

61000.0

In [38]:
my_series.iloc[4]    # 배열 번호로 접근

61000.0

In [39]:
my_series.loc['2020-09-15':'2020-09-17']  # 인덱스로 Slicing

2020-09-15    61000.0
2020-09-16    61000.0
2020-09-17    59500.0
Name: A005930, dtype: float64

In [40]:
my_series.iloc[4:7]    # 배열 번호로 Slicing (끝 포함 X)

2020-09-15    61000.0
2020-09-16    61000.0
2020-09-17    59500.0
Name: A005930, dtype: float64

In [41]:
my_series.iloc[4:] + my_series.iloc[4:]

2020-09-15    122000.0
2020-09-16    122000.0
2020-09-17    119000.0
2020-09-18    118600.0
Name: A005930, dtype: float64

In [42]:
my_series.loc['2020-09-15'::2] + 30000  # Scalar Broadcasting

2020-09-15    91000.0
2020-09-17    89500.0
Name: A005930, dtype: float64

In [43]:
my_series.iloc[4:].mean()    # 평균 aggregation

60200.0

In [44]:
new_sr = pd.Series([11,22,3,45], name='apple',
                   index=['a','b','xs','e11'])
new_sr

a      11
b      22
xs      3
e11    45
Name: apple, dtype: int64

#### pandas 기본 3. 『 DataFrame 』 행×열 데이터 

In [45]:
# 불러온 주가 데이터에서 불러오고, dataframe 하나를 추출합니다.
my_df = 주가_데이터.T.loc['2020-09-09':,'A005900':'A006000']

In [46]:
my_df

Symbol      A005930  A005940  A005950  A005960  A005980  A005990
2020-09-09  58400.0   9190.0   9080.0  11000.0    671.0   7990.0
2020-09-10  59200.0   9280.0   9280.0  11150.0    671.0   7960.0
2020-09-11  59000.0   9270.0   9360.0  11050.0    671.0   8120.0
2020-09-14  60400.0   9370.0   9400.0  11200.0    671.0   8200.0
2020-09-15  61000.0   9470.0   9390.0  11350.0    671.0   8180.0
2020-09-16  61000.0   9530.0   9080.0  11250.0    671.0   8180.0
2020-09-17  59500.0   9320.0   8880.0  11000.0    671.0   8000.0
2020-09-18  59300.0   9320.0   9070.0  10850.0    671.0   8020.0

In [53]:
my_df.iloc[0,0]

58400.0

#### pandas 기본 4. 『 DataFrame 』  접근

In [47]:
my_df.loc['2020-09-15', 'A005930']   # .loc 단일 원소 접근

61000.0

In [48]:
# .loc [ 인덱스, 컬럼 slice ] 로 접근  →  Series 반환
my_df.loc['2020-09-15', 'A005930':'A005950']

Symbol
A005930    61000.0
A005940     9470.0
A005950     9390.0
Name: 2020-09-15, dtype: float64

In [49]:
# .loc [ 인덱스 slice, 컬럼이름 ] 으로 접근  →  Series 반환
my_df.loc['2020-09-15':'2020-09-18', 'A005930']

2020-09-15    61000.0
2020-09-16    61000.0
2020-09-17    59500.0
2020-09-18    59300.0
Name: A005930, dtype: float64

In [54]:
#  .loc [ index slice, column slice ]  →  DataFrame 반환
my_df.loc['2020-09-14':'2020-09-18':2, 'A005940':'A005980']

Symbol      A005940  A005950  A005960  A005980
2020-09-14   9370.0   9400.0  11200.0    671.0
2020-09-16   9530.0   9080.0  11250.0    671.0
2020-09-18   9320.0   9070.0  10850.0    671.0

In [55]:
# .iloc [ index, column slice ]  으로 접근  →  Series 반환
my_df.iloc[0, 3:]  

Symbol
A005960    11000.0
A005980      671.0
A005990     7990.0
Name: 2020-09-09, dtype: float64

In [56]:
#  .iloc [ index slice, column slice ]  →  DataFrame 반환
my_df.iloc[4:7:2, 1:4]

Symbol      A005940  A005950  A005960
2020-09-15   9470.0   9390.0  11350.0
2020-09-17   9320.0   8880.0  11000.0

In [57]:
# ::으로 모든 원소 지칭
my_df.loc[::, 'A005930']

2020-09-09    58400.0
2020-09-10    59200.0
2020-09-11    59000.0
2020-09-14    60400.0
2020-09-15    61000.0
2020-09-16    61000.0
2020-09-17    59500.0
2020-09-18    59300.0
Name: A005930, dtype: float64

In [58]:
# : 한번만 사용 가능
my_df.iloc[5, :]

Symbol
A005930    61000.0
A005940     9530.0
A005950     9080.0
A005960    11250.0
A005980      671.0
A005990     8180.0
Name: 2020-09-16, dtype: float64

In [59]:
# shape 보기
my_df.iloc[5, :].shape

(6,)

In [60]:
my_df.iloc[5:, ::3]

Symbol      A005930  A005960
2020-09-16  61000.0  11250.0
2020-09-17  59500.0  11000.0
2020-09-18  59300.0  10850.0

In [61]:
my_df.iloc[5:, ::3].shape

(3, 2)

In [62]:
my_df.iloc[::4].loc[:, 'A005950':]

Symbol      A005950  A005960  A005980  A005990
2020-09-09   9080.0  11000.0    671.0   7990.0
2020-09-15   9390.0  11350.0    671.0   8180.0

In [63]:
my_df.loc['2020-09-09'::4].iloc[:,2:]

Symbol      A005950  A005960  A005980  A005990
2020-09-09   9080.0  11000.0    671.0   7990.0
2020-09-15   9390.0  11350.0    671.0   8180.0

In [64]:
my_df_2 = my_df.loc[:'2020-09-11','A005960':]

In [65]:
my_df_2

Symbol      A005960  A005980  A005990
2020-09-09  11000.0    671.0   7990.0
2020-09-10  11150.0    671.0   7960.0
2020-09-11  11050.0    671.0   8120.0

In [66]:
my_df_2 * 1.30   # Broadcasting

Symbol      A005960  A005980  A005990
2020-09-09  14300.0    872.3  10387.0
2020-09-10  14495.0    872.3  10348.0
2020-09-11  14365.0    872.3  10556.0

In [67]:
my_df_2.mean(axis=0)  # 평균 Agg

Symbol
A005960    11066.666667
A005980      671.000000
A005990     8023.333333
dtype: float64